config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :products
  post "products/:product_id/add_to_cart", to: "products#add_product_to_cart", as: :add_to_cart
  delete "products/:product_id/remove_to_cart", to: "products#remove_product_to_cart", as: :remove_to_cart
  delete "product/:product_id/remove_all_from_cart", to: "products#remove_all_from_cart", as: :remove_all_from_cart
  resources :products, module: "products" do
    resources :photos
  end

  devise_for :users, controllers: {
    sessions: "user/sessions",
    registrations: "user/registrations"
  }
  namespace :user do
    get "about", to: "user#about", as: :about
    resources :addresses
    resources :carts
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "main#dashboard"
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_product
  has_many :products, through: :cart_product
  validates :user_id, uniqueness: true

  after_initialize do |cart|
    price = 0
    cart.products.each { |product|
      price += product.current_price
    }
    cart.price = price
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :addresses
  has_many :orders
  has_one :cart
  has_many :products, through: :cart
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :first_name, :last_name, presence: true, length: { in: 3..15 }
  validates :birthdate, comparison: { less_than: 5.years.ago.to_date, message: "You must be 5 years old."}

  before_save do |user|
    user.age = ((Time.zone.now - user.birthdate.to_time) / 1.year.seconds).floor
  end

  after_create_commit do |user|
    Cart.create(user_id: user.id)
  end

  after_destroy_commit do
    Cart.where(user_id: user.id).delete
  end
end

app/controllers/user/addresses_controller.rb
class User::AddressesController < ApplicationController
  before_action :set_address, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /addresses or /addresses.json
  def index
    @addresses = current_user.addresses
  end

  # GET /addresses/1 or /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @user = current_user
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses or /addresses.json
  def create
    @user = current_user
    @address = @user.addresses.new(address_params)

    respond_to do |format|
      if @address.save
        format.html { redirect_to user_addresses_url, notice: "Address was successfully created." }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1 or /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to user_addresses_url, notice: "Address was successfully updated." }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1 or /addresses/1.json
  def destroy
    @address.destroy!

    respond_to do |format|
      format.html { redirect_to addresses_path, status: :see_other, notice: "Address was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def address_params
      params.require(:address).permit(:address_type, :address, :city, :state, :country, :zipcode, :is_active)
    end
end

app/controllers/user/carts_controller.rb
class User::CartsController < ApplicationController
  before_action :set_cart, only: %i[ show edit update destroy ]

  # GET /carts or /carts.json
  def index
    @cart = current_user.cart
    @products = @cart.products.distinct.page(params[:page]).per(2)
    @number = @cart.products.group(:id).count(:id)
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts or /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: "Cart was successfully created." }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1 or /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1 or /carts/1.json
  def destroy
    @cart.destroy!

    respond_to do |format|
      format.html { redirect_to carts_path, status: :see_other, notice: "Cart was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find_by(user_id: current_user.id)
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.require(:cart).permit(:user_id, :product_id, :price)
    end
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :attribute, :first_name, :last_name, :birthdate ])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [ :attribute, :first_name, :last_name, :birthdate ])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after updating user.
  def after_update_path_for(resource)
    user_about_path
  end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/user_controller.rb
class User::UserController < ApplicationController
  def about
    @user = current_user
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/user/carts/_cart.html.erb
<div id="<%= dom_id cart %>">
  <p>
    <strong>User:</strong><%= current_user.email %>
  </p>
  
  <p>
    <strong>Price:</strong>
    <%= cart.price %>
  </p>

  <p>
    <strong>Place Order:</strong>
    <%= link_to "Place Order", new_order_path(:orders => @number, :actions => "cart") %>
  </p>

  <%= paginate @products %>

  <p>
    <strong>Product:</strong>
    <% @products.each do |product| %>
    <%= render partial: "product", locals: { product: product } %>
    <strong>Quantity:</strong>
    <%= link_to "-", remove_to_cart_path(product.id), data: { turbo_method: :delete} %>
    <%= @number[product.id] %> 
    <%= link_to "+", add_to_cart_path(product), data: { turbo_method: :post} %>
    <p>
      <%= link_to "Show this product", product %> |
      <%= link_to "Remove to Cart", remove_all_from_cart_path(product.id), data: { turbo_method: :delete} %> |
      <%= link_to "Buy Now", product %>
    </p>
  <% end %>
  </p>

  

</div>

app/views/user/carts/_form.html.erb
<%= form_with(model: [:user, cart]) do |form| %>
  <% if cart.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
        <% cart.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :product_id, style: "display: block" %>
    <%= form.text_field :product_id %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/user/carts/_product.html.erb
<div id="<%= dom_id product %>">
  <% product.photos.each do |photo| %>
  <span>
    <%= image_tag url_for(photo.photo), height:200, width:200 if photo.photo.attached? %>
    </span>
  <% end %>
  <p>
    <strong>Id:</strong>
    <%= product.id %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= product.price %>
  </p>

  <p>
    <strong>Discount:</strong>
    <%= product.discount %>%
  </p>

  <p>
    <strong>You are Saving:</strong>
    <%= product.compare_at_price %>
  </p>

  <p>
    <strong>Currently available at:</strong>
    <%= product.current_price %>
  </p>

  <p>
    <strong>Is active:</strong>
    <%= product.is_active %>
  </p>

</div>

app/views/user/carts/edit.html.erb
<% content_for :title, "Editing cart" %>

<h1>Editing cart</h1>

<%= render "form", cart: @cart %>

<br>

<div>
  <%= link_to "Show this cart", user_cart_path %> |
  <%= link_to "Back to carts", user_carts_path %>
</div>

app/views/user/carts/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Carts" %>

<h1>Cart</h1>

<div id="carts">
<%= render partial: "cart", locals: { cart: @cart } %>
</div>

app/views/user/carts/new.html.erb
<% content_for :title, "New cart" %>

<h1>New cart</h1>

<%= render "form", cart: @cart %>

<br>

<div>
  <%= link_to "Back to carts", user_carts_path %>
</div>

app/views/user/carts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @cart %>

<div>
  <%= link_to "Edit this cart", edit_user_cart_path(id: current_user.id) %> |
  <%= link_to "Back to carts", user_carts_path %>

  <%= button_to "Destroy this cart", user_cart_path, method: :delete %>
</div>