config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :products
  post "products/:product_id/add_to_cart", to: "products#add_product_to_cart", as: :add_to_cart
  delete "products/:product_id/remove_to_cart", to: "products#remove_product_to_cart", as: :remove_to_cart
  delete "product/:product_id/remove_all_from_cart", to: "products#remove_all_from_cart", as: :remove_all_from_cart
  resources :products, module: "products" do
    resources :photos
  end

  devise_for :users, controllers: {
    sessions: "user/sessions",
    registrations: "user/registrations"
  }
  namespace :user do
    get "about", to: "user#about", as: :about
    resources :addresses
    resources :carts
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "main#dashboard"
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :address
  has_many :order_products
  has_many :products, through: :order_products
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ show edit update destroy ]

  # GET /orders or /orders.json
  def index
    @orders = current_user.orders
    # @products = @order.products.distinct
    # @number = @order.products.group(:id).count(:id)
  end

  # GET /orders/1 or /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @addresses = current_user.addresses
    @address_options = []
    @addresses.each { |address|
      @address_options << [ address.values_at(:address_type, :address, :city).join(","), address.id ]
    }
    @orders = params[:orders]
    @order_price = 0
    @products_ids = []
    unless @orders
      flash[:alert] = "On product is mentioned."
    else
      @orders.each { |key, value|
        @product = Product.find(key)
        @order_price += @product.price * Integer(value)
        @products_ids << Array.new(Integer(value), @product.id)
      }
    end
    @hidden_params = { products_id: @products_ids, order_price: @order_price }
    # puts "Address options #{@address_options}"

    @order = Order.new()
  end

  # GET /orders/1/edit
  def edit
  end

  def empty_cart
    @cart = current_user.cart
    @cart.products = []
    @cart.save
  end

  # POST /orders or /orders.json
  def create
    @products_ids = order_params[:products_id].split(" ").map(&:to_i)
    puts "Products_ids:" + "#{@products_ids}"
    if @products_ids == []
      return redirect_to products_url, orders: @number, alert: "Add products to cart first or buy a product."
    end
    @order = Order.new(order_params.merge(user_id: current_user.id).except(:products_id, :actions))
    respond_to do |format|
      if @order.save
        @products_ids.each { |id|
          @@product = Product.find(id)
          @@product_order = @order.order_products.new()
          @@product_order.product_id = @@product.id
          @@product_order.product_price = @@product.current_price
          @@product_order.save
          puts @@product_order.errors.full_messages
        }
        if order_params[:actions]
          if order_params[:actions] == "cart"
            puts "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG "
            empty_cart
          end
        end
        format.html { redirect_to @order, notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @ord_pro = OrderProduct.find(@order.order_products.ids[0])
    @ord_pro.destroy!
    @order.destroy!

    respond_to do |format|
      format.html { redirect_to orders_path, status: :see_other, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:user_id, :address_id, :products_id, :order_price, :actions)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_with(model: @order) do |form| %>
  <% if @order.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% @order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
      <%= puts @address_options %>
      <%= form.label :address_id, style: "display: block" %>
      <%= form.select :address_id, @address_options %>
      <%= link_to "New address", new_user_address_path %>
  </div>

  <div>
    <%= form.label :order_price, style: "display: block" %>
    <%= form.text_field :order_price, value: @hidden_params[:order_price] %>
  </div>

  <div>
    
    <%= form.text_field :products_id, value: @hidden_params[:products_id] %>
  </div>

  <div>
    <% if @address_options == [] %>
      <%= link_to "New address", new_user_address_path %>
    <% else %>
    <%= form.hidden_field :actions, value: params[:actions] %>
      <%= form.submit %>
    <% end %>
    
  </div>
<% end %>

app/views/orders/_order.html.erb
<div id="<%= dom_id order %>">
  <p>
    <strong>Addresses:</strong>
    <%= Address.find(order.address_id).values_at(:id, :address_type, :address, :city).join("\n") %>
  </p>

  <p>
    <strong>Products:</strong>
    <% number =  order.products.group(:id).count(:id) %>
    <strong>Product:</strong>
    <% order.products.distinct.each do |product| %>
    <%= render partial: "product", locals: { product: product } %>
    <strong>Quantity:</strong>
    <%= number[product.id] %> 

    <%= link_to "Show this product", product %>
    <% end %>
  </p>

  <p>
    <strong>Order price:</strong>
    <%= order.order_price %>
  </p>
</div>

app/views/orders/_product.html.erb
<div id="<%= dom_id product %>">
  <% photo = product.photos.first %>
  <span>
    <%= image_tag url_for(photo.photo), height:200, width:200 if photo.photo.attached? %>
  </span>
  
  <p>
    <strong>Name:</strong>
    <%= product.name %>
  </p>
  <p>
    <strong>Price:</strong>
    <%= product.price %>
  </p>

  <p>
    <strong>Discount:</strong>
    <%= product.discount %>%
  </p>

  <p>
    <strong>You Saved:</strong>
    <%= product.compare_at_price %>
  </p>

  <p>
    <strong>Currently available at:</strong>
    <%= product.current_price %>
  </p>

</div>

app/views/orders/edit.html.erb
<% content_for :title, "Editing order" %>

<h1>Editing order</h1>

<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Show this order", @order %> |
  <%= link_to "Back to orders", orders_path %>
</div>

app/views/orders/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Orders" %>

<h1>Orders</h1>
    <table id="example">
        <thead>
            <tr>
                <th>Order ID</th>
                <th>Addresses</th>
                <th>Products</th>
                <th>Quantity</th>
                <th>Order Price</th>
                <th>Order Destroy</th>
            </tr>
        </thead>
        <tbody>
            
                <% @orders.each do |order| %>
                <tr>
                    <td><%= order.id %></td>
                    <td><%= Address.find(order.address_id).values_at(:id, :address_type, :address, :city).join("\n") %></td>
                    <td><%= order.product_ids %></td>
                    <td><%= order.products.group(:id).count(:id) %></td>
                    <td><%= order.order_price %></td>
                    <td><%= link_to "Cancel Order", order_path(order.id), data: { turbo_method: :delete , turbo_confirm: "Are you sure?"} %></td>
                    </tr>
                <% end %>
            
        </tbody>
            
        <tfoot>
            <tr>
                <th>Order ID</th>
                <th>Addresses</th>
                <th>Products</th>
                <th>Quantity</th>
                <th>Order Price</th>
            </tr>
        </tfoot>

    </table>
<div id="orders">
  <% @orders.each do |order| %>
    <%= render order %>
    <p>
      <%= link_to "Show this order", order %>
    </p>
    <hr/>
  <% end %>
  
</div>

<%= link_to "New order", new_order_path %>

app/views/orders/new.html.erb
<% content_for :title, "New order" %>

<h1>New order</h1>

<%= render "form", locals: {order: @order, hidden_params: @hidden_params, address_options: @address_options} %>

<br>

<div>
  <%= link_to "Back to orders", orders_path %>
</div>

app/views/orders/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @order %>

<div>
  <%= link_to "Edit this order", edit_order_path(@order) %> |
  <%= link_to "Back to orders", orders_path %>

  <%= button_to "Destroy this order", @order, method: :delete %>
</div>