config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :products
  post "products/:product_id/add_to_cart", to: "products#add_product_to_cart", as: :add_to_cart
  delete "products/:product_id/remove_to_cart", to: "products#remove_product_to_cart", as: :remove_to_cart
  delete "product/:product_id/remove_all_from_cart", to: "products#remove_all_from_cart", as: :remove_all_from_cart
  resources :products, module: "products" do
    resources :photos
  end

  devise_for :users, controllers: {
    sessions: "user/sessions",
    registrations: "user/registrations"
  }
  namespace :user do
    get "about", to: "user#about", as: :about
    resources :addresses
    resources :carts
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "main#dashboard"
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :photos, as: :photoable
  has_many :order_products
  has_many :orders, through: :order_products
  has_many :cart_product
  has_many :carts, through: :cart_product
  has_many :users, through: :carts
  validates :price, :discount, :description, :name, presence: true
  validates :name, length: { in: 3..100 }
  validates :description, length: { minimum: 5 }
  validates :price, numericality: { greater_than: 0 }
  validates :discount, numericality: { in: 0..99 }
  before_save do |product|
    product.compare_at_price = (product.price * (product.discount/100.00)).floor
  end

  after_find do |product|
    product.current_price = (product.price - product.compare_at_price).floor
  end
end

app/controllers/products/photos_controller.rb
class Products::PhotosController < ApplicationController
  before_action :set_photo, only: %i[ show edit update destroy ]

  # GET /photos or /photos.json
  def index
    @product = Product.find(params["product_id"])
    @photos = @product.photos
  end

  # GET /photos/1 or /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @product = Product.find(params["product_id"])
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos or /photos.json
  def create
    puts params
    @product = Product.find(params["product_id"])
    @photo = Photo.new(photo_params.merge(photoable_id: params["product_id"], photoable_type: "Product"))
    respond_to do |format|
      if @photo.save
        format.html { redirect_to product_photos_url, notice: "Photo was successfully created." }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1 or /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: "Photo was successfully updated." }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1 or /photos/1.json
  def destroy
    @photo.destroy!

    respond_to do |format|
      format.html { redirect_to product_photos_path, status: :see_other, notice: "Photo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def photo_params
      params.require(:photo).permit(:photo)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]
  before_action :image_attached, only: [ :show ]

  # GET /products or /products.json
  def index
    @products = Product.page(params[:page]).per(3)
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy!

    respond_to do |format|
      format.html { redirect_to products_path, status: :see_other, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def add_product_to_cart
    @product = Product.find(params["product_id"])
    @user_cart = current_user.cart.products
    @user_cart << @product
    redirect_to user_carts_url
  end

  def remove_product_to_cart
    @product = Product.find(params["product_id"])
    @cart = current_user.cart
    CartProduct.where("cart_id = ? AND product_id = ?", @cart.id, @product.id).first.delete
    redirect_to user_carts_url
  end

  def remove_all_from_cart
    @product = Product.find(params["product_id"])
    @cart = current_user.cart
    CartProduct.where("cart_id = ? AND product_id = ?", @cart.id, @product.id).delete_all
    redirect_to user_carts_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :discount, :is_active)
    end

    # check_image attached
    def image_attached
      if @product.photos == []
        flash[:notice] = "Add photos to your product for better reach."
      end
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.label :discount, style: "display: block" %>
    <%= form.number_field :discount %>
  </div>

  <div>
    <%= form.label :is_active, style: "display: block" %>
    <%= form.check_box :is_active %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div class="card-body">
  <% if params[:action] == "index" %>
    <% photo = product.photos.first.photo %>
    <span>
      <%= image_tag url_for(photo), height:200, width:200 if photo.attached? %>
    </span>
  <% else %>
  <% product.photos.each do |photo| %>
    <span>
      <%= image_tag url_for(photo.photo), height:200, width:200 if photo.photo.attached? %>
    </span>
  <% end %>
  <% end %>
  <ul class="list-group list-group-flush">
    <h6 class="list-group-item">
      <strong>Name:</strong>
      <%= 
      if params[:action] == "index"    
        truncate(product.name)
      else
        product.name
      end  %>
    </h6>
    <% unless params[:action] == "index" %>
    <li class="list-group-item">
      <strong>Description:</strong>
      <%= product.description %>
    </li>
    <% end %>
    <li class="list-group-item">
      <strong>Price:</strong>
      <%= product.price %>
    </li>

    <li class="list-group-item">
      <strong>Discount:</strong>
      <%= product.discount %>%
    </li>

    <li class="list-group-item">
      <strong>You are Saving:</strong>
      <%= product.compare_at_price %>
    </li>

    <li class="list-group-item">
      <strong>Currently available at:</strong>
      <%= product.current_price %>
    </li>

    <li class="list-group-item">
      <strong>Is active:</strong>
      <%= product.is_active %>
    </li>
  </ul>

</div>

app/views/products/edit.html.erb
<% content_for :title, "Editing product" %>

<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Products" %>

<h1>Products</h1> 

<nav aria-label="Page navigation example">
  <div class="d-flex justify-content-around">
    <%= paginate @products %>
    <ul class="pagination">
      <li class="page-item"><%= link_to_prev_page @products, 'Previous', class:"page-link" %></li>
      <li class="page-item"><%= link_to_next_page @products, 'Next', class:"page-link" %></li>
    </ul>
    <div><%= page_entries_info @products, entry_name: 'product' %></div>
    <%= link_to "Add New product", new_product_path %>
  </div>
</nav>

<div id="products" class="d-flex justify-content-evenly">
  <% @products.each do |product| %>
    <div class="card">
      <%= render product %>
      <div class="card-footer">
        <%= link_to "Show this product", product %> |
        <%= link_to "Add to Cart", add_to_cart_path(product), data: { turbo_method: :post} %> |
        <%= link_to "Buy Now", new_order_path(:orders => {product.id => 1}) %>
      </div>
    </div>
  <% end %>
</div>
<div class="d-flex justify-content-around">
<%= paginate @products %>
<%= link_to "New product", new_product_path %>
</div>

app/views/products/new.html.erb
<% content_for :title, "New product" %>

<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<% {notice: ("can't be empty")}  if @product.photos == [] %>
<div class="card">
<%= render @product %>

<div class="card-footer">
  <%= link_to "Edit this product", edit_product_path(@product) %> |
  <%= link_to "Back to products", products_path %> |
  <%= link_to "Add Image of Product", new_product_photo_path(@product) %>

  <%= button_to "Destroy this product", @product, method: :delete %>
</div>
</div>