config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :products
  post "products/:product_id/add_to_cart", to: "products#add_product_to_cart", as: :add_to_cart
  delete "products/:product_id/remove_to_cart", to: "products#remove_product_to_cart", as: :remove_to_cart
  delete "product/:product_id/remove_all_from_cart", to: "products#remove_all_from_cart", as: :remove_all_from_cart
  resources :products, module: "products" do
    resources :photos
  end

  devise_for :users, controllers: {
    sessions: "user/sessions",
    registrations: "user/registrations"
  }
  namespace :user do
    get "about", to: "user#about", as: :about
    resources :addresses
    resources :carts
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "main#dashboard"
end

app/views/layouts/_footer.html.erb
<!-- Remove the container if you want to extend the Footer to full width. -->
<footer class="text-center" style="background-color: grey;">

  <!-- Copyright -->
  <div class="text-center text-white p-3">
    © 2024 Copyright:
    <a class="text-white" href="https://infotech.works/">infotech.works</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- End of .container -->

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary shadow p-3 mb-2 bg-body-tertiary rounded ">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= root_url%>">OrderManager</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%= products_url %>">Products</a>
        </li>
        </ul>
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <% if user_signed_in? %>
          <li><a class="nav-link active" href="<%= user_about_url %>">User Profile</a></li>
          <li><a class="nav-link active" href="<%= edit_user_registration_url %>">Edit Profile</a></li>
          <li><a class="nav-link active" href="<%= user_addresses_url %>">My Address</a></li>
          <li><a class="nav-link active" href="<%= user_carts_url %>">My Cart</a></li>
          <li><a class="nav-link active" href="<%= orders_url %>">My Order</a></li>
          <li class="nav-item"><%= link_to "Sign Out", destroy_user_session_path, data: { turbo_method: :delete , turbo_confirm: "Are you sure?"}, class: "nav-link active" %></li>
          <% else %>
          <li class="nav-item"><a class="nav-link active" aria-current="page" href="<%= new_user_registration_url %>">Sign Up</a></li>
          <li class="nav-item"><a class="nav-link active" aria-current="page" href="<%= new_user_session_url %>">Sign In</a></li>
          <% end %>
        </ul>
    </div>
  </div>
</nav>
<div><%= notice %></div>
<div><%= alert %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Order Manager" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link rel="stylesheet" href="https://cdn.datatables.net/2.1.0/css/jquery.dataTables.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "https://cdn.jsdelivr.net/npm/jquery-validation@1.17.0/dist/jquery.validate.min.js", async: true, onload: "myInit()" %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div class="card">
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.datatables.net/2.1.0/js/jquery.dataTables.min.js"></script>
<script>
let table = new DataTable('#example');
 
table.on('click', 'tbody tr', function () {
    let data = table.row(this).data();
 
    alert('You clicked on ' + data[0] + "'s row");
});
</script>
</html>